project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!Student_Work/"

website:
  title: "Math221 Notebook"
  navbar:
    background: primary
    search: true
    left:
    - text: "Unit 1"
      menu:
        - text: "Data Literacy"
        - href: ./1-Data_Literacy/1-Course_Introduction.qmd
        - href: ./1-Data_Literacy/2-Stat_Process.qmd
        - href: ./1-Data_Literacy/3-Statistical_Process_Practice.qmd
        - href: ./1-Data_Literacy/4-Installing_R.qmd
        - href: ./1-Data_Literacy/5-Shape_and_Center.qmd
        - href: ./1-Data_Literacy/6-Spread.qmd
        - href: ./1-Data_Literacy/7-Introducing_R_Practice.qmd
        - href: ./1-Data_Literacy/8-Summarizing_Data_Multiple_Groups.qmd
        - href: ./1-Data_Literacy/9-Summarizing_Data_Practice.qmd
        - href: ./1-Data_Literacy/10-AA_Data_Summaries.qmd
        
    - text:  "Unit 2"
      menu:
        - text: "Into the Tidyverse"
        - href: ./2-Tidy_Data/01-Wrangling_Basics.qmd
        - href: ./2-Tidy_Data/02-Filter.qmd
        - href: ./2-Tidy_Data/03-Select.qmd
        - href: ./2-Tidy_Data/04-Tidyverse_Fundamentals.qmd
        - href: ./2-Tidy_Data/05-Exploring_New_Data_With_Tidyverse.qmd
        - href: ./2-Tidy_Data/06-GGPlot_Intro.qmd
        - text: "Bonus Material"
        - href: ./2-Tidy_Data/Bonus_More_Tidy_Practice.qmd
        - href: ./2-Tidy_Data/Bonus_Mutate.qmd
        - href: ./2-Tidy_Data/Bonus_GroupBy_Summarise.qmd

        
    - text: "Unit 3"
      menu:
         - text: "Fundamentals of Statistics"
         - href: ./3-Stat_Fundamentals/01-Intro_to_Probability.qmd
         - href: ./3-Stat_Fundamentals/02-The_Normal_Distribution_Textbook.qmd
         - href: ./3-Stat_Fundamentals/03-Normal_Distribution_Workbook.qmd
         - href: ./3-Stat_Fundamentals/04-Normal_Probability_Practice.qmd
         - href: ./3-Stat_Fundamentals/05-The_Central_Limit_Theorem.qmd
         - href: ./3-Stat_Fundamentals/06-Central_Limit_Theorem_Practice.qmd
         - href: ./3-Stat_Fundamentals/07-Prob_Calculations_for_Means.qmd
         - href: ./3-Stat_Fundamentals/08-CLT_Normal_Prob_for_Means.qmd
         - href: ./3-Stat_Fundamentals/09-Prob_Calculations_for_Means_Practice.qmd
         - href: ./3-Stat_Fundamentals/10-Assessing_Normality.qmd
  
    - text: "Unit 4"
      menu:
        - text: "Statistical Tests - Part 1"
        - href: ./4-Statistical_Tests_Part1/01-Inference_for_mean_sigma_unknown.qmd
        - href: ./4-Statistical_Tests_Part1/02-AA_Hypothesis_Conf_Int.qmd
        - href: ./4-Statistical_Tests_Part1/03-Paired_ttest.qmd
        - href: ./4-Statistical_Tests_Part1/05-Independent_2_sample_ttest.qmd
        - href: ./4-Statistical_Tests_Part1/07-ANOVA_Intro.qmd
        - href: ./4-Statistical_Tests_Part1/09-AA_Unit4_Review.qmd

    - text: "Unit 5"
      menu:
        - text: "Statistical Tests - Part 2"
        - href: ./5-Statistical_Tests_Part2/01-Bivariate_Data_Intro.qmd
        - href: ./5-Statistical_Tests_Part2/02-Linear_Regression_Intro.qmd
        - href: ./5-Statistical_Tests_Part2/03-Regression_Practice.qmd
        - href: ./5-Statistical_Tests_Part2/05-Distribution_of_Phat.qmd
        - href: ./5-Statistical_Tests_Part2/07-One_Sample_Proportion_Ztest.qmd
        - href: ./5-Statistical_Tests_Part2/09-Two_Sample_Proportion_Ztest.qmd
        - href: ./5-Statistical_Tests_Part2/11-Chi_Square_Intro.qmd
        - href: ./5-Statistical_Tests_Part2/13-AA_Who_Shot_First_Cat_Vars.qmd

    - text: "Semester Project"
      menu:
        - href: ./6-Semester_Project/Importing_Data.qmd
        - href: ./6-Semester_Project/Semester_Project_Instructions.qmd

    - text: "R Help"
      menu:
        - text: "Tidyverse Cheat Sheet"
          href: https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf
        - text: "R for Data Science"
          href: https://r4ds.had.co.nz/transform.html
        - href: ./1-Data_Literacy/4-Installing_R.qmd
        - href: ./2-Tidy_Data/06-GGPlot_Intro.qmd
        - href: ./2-Tidy_Data/01-Wrangling_Basics.qmd
        - href: ./2-Tidy_Data/02-Filter.qmd
        - href: ./2-Tidy_Data/03-Select.qmd
        - href: ./2-Tidy_Data/Bonus_Mutate.qmd
        - href: ./2-Tidy_Data/Bonus_GroupBy_Summarise.qmd
        - href: ./6-Semester_Project/Importing_Data.qmd

format:  
  html:
    theme:
      light: flatly
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true

output-dir: docs
